/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface WildlifeDAOInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DAO_FEE"
      | "MAX_DONATION"
      | "MIN_DONATION"
      | "MIN_VOTE_POWER"
      | "VOTE_COST"
      | "VOTING_PERIOD"
      | "checkVoteEligibility"
      | "debugProjectStatus"
      | "donate"
      | "exchangeRate"
      | "getProjectState"
      | "owner"
      | "projectCount"
      | "projects"
      | "proposalIdToProjectId"
      | "renounceOwnership"
      | "submitProject"
      | "totalValueLocked"
      | "totalWLD"
      | "transferOwnership"
      | "voteOnProject"
      | "wldToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DonationReceived"
      | "OwnershipTransferred"
      | "ProjectStatusChanged"
      | "ProposalSubmitted"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(functionFragment: "DAO_FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_DONATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_DONATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_VOTE_POWER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "VOTE_COST", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "VOTING_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkVoteEligibility",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "debugProjectStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "donate",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "exchangeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectState",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "projectCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "projects",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalIdToProjectId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitProject",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalValueLocked",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "totalWLD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voteOnProject",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "wldToken", values?: undefined): string;

  decodeFunctionResult(functionFragment: "DAO_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DONATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_DONATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_VOTE_POWER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "VOTE_COST", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "VOTING_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkVoteEligibility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "debugProjectStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "exchangeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "projectCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "projects", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalIdToProjectId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalValueLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalWLD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteOnProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wldToken", data: BytesLike): Result;
}

export namespace DonationReceivedEvent {
  export type InputTuple = [
    donor: AddressLike,
    usdAmount: BigNumberish,
    wldMinted: BigNumberish,
    daoFeeAmount: BigNumberish
  ];
  export type OutputTuple = [
    donor: string,
    usdAmount: bigint,
    wldMinted: bigint,
    daoFeeAmount: bigint
  ];
  export interface OutputObject {
    donor: string;
    usdAmount: bigint;
    wldMinted: bigint;
    daoFeeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectStatusChangedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    oldStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    oldStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalSubmittedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    submitter: AddressLike,
    title: string,
    fundingRequired: BigNumberish,
    status: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    submitter: string,
    title: string,
    fundingRequired: bigint,
    status: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    submitter: string;
    title: string;
    fundingRequired: bigint;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    voter: AddressLike,
    support: boolean,
    votingPower: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    voter: string,
    support: boolean,
    votingPower: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    voter: string;
    support: boolean;
    votingPower: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WildlifeDAO extends BaseContract {
  connect(runner?: ContractRunner | null): WildlifeDAO;
  waitForDeployment(): Promise<this>;

  interface: WildlifeDAOInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DAO_FEE: TypedContractMethod<[], [bigint], "view">;

  MAX_DONATION: TypedContractMethod<[], [bigint], "view">;

  MIN_DONATION: TypedContractMethod<[], [bigint], "view">;

  MIN_VOTE_POWER: TypedContractMethod<[], [bigint], "view">;

  VOTE_COST: TypedContractMethod<[], [bigint], "view">;

  VOTING_PERIOD: TypedContractMethod<[], [bigint], "view">;

  checkVoteEligibility: TypedContractMethod<
    [projectId: BigNumberish, voter: AddressLike],
    [[boolean, string] & { isEligible: boolean; reason: string }],
    "view"
  >;

  debugProjectStatus: TypedContractMethod<
    [projectId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        status: bigint;
        currentTime: bigint;
        votingStartTime: bigint;
        votingEndTime: bigint;
        canVoteNow: boolean;
      }
    ],
    "view"
  >;

  donate: TypedContractMethod<
    [_usdAmount: BigNumberish, _recipient: AddressLike],
    [void],
    "payable"
  >;

  exchangeRate: TypedContractMethod<[], [bigint], "view">;

  getProjectState: TypedContractMethod<
    [projectId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        status: bigint;
        votingStartTime: bigint;
        votingEndTime: bigint;
        forVotes: bigint;
        againstVotes: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  projectCount: TypedContractMethod<[], [bigint], "view">;

  projects: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        title: string;
        description: string;
        proposer: string;
        fundingRequired: bigint;
        fundingReceived: bigint;
        status: bigint;
        submissionTime: bigint;
        forVotes: bigint;
        againstVotes: bigint;
        votingStartTime: bigint;
        votingEndTime: bigint;
        executed: boolean;
        proposalId: string;
      }
    ],
    "view"
  >;

  proposalIdToProjectId: TypedContractMethod<[arg0: string], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  submitProject: TypedContractMethod<
    [
      proposalId: string,
      title: string,
      description: string,
      fundingRequired: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  totalValueLocked: TypedContractMethod<[], [bigint], "view">;

  totalWLD: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  voteOnProject: TypedContractMethod<
    [projectId: BigNumberish, support: boolean],
    [void],
    "nonpayable"
  >;

  wldToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DAO_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DONATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_DONATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_VOTE_POWER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOTE_COST"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOTING_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkVoteEligibility"
  ): TypedContractMethod<
    [projectId: BigNumberish, voter: AddressLike],
    [[boolean, string] & { isEligible: boolean; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "debugProjectStatus"
  ): TypedContractMethod<
    [projectId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        status: bigint;
        currentTime: bigint;
        votingStartTime: bigint;
        votingEndTime: bigint;
        canVoteNow: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "donate"
  ): TypedContractMethod<
    [_usdAmount: BigNumberish, _recipient: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "exchangeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProjectState"
  ): TypedContractMethod<
    [projectId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        status: bigint;
        votingStartTime: bigint;
        votingEndTime: bigint;
        forVotes: bigint;
        againstVotes: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "projectCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "projects"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        title: string;
        description: string;
        proposer: string;
        fundingRequired: bigint;
        fundingReceived: bigint;
        status: bigint;
        submissionTime: bigint;
        forVotes: bigint;
        againstVotes: bigint;
        votingStartTime: bigint;
        votingEndTime: bigint;
        executed: boolean;
        proposalId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposalIdToProjectId"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitProject"
  ): TypedContractMethod<
    [
      proposalId: string,
      title: string,
      description: string,
      fundingRequired: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalValueLocked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalWLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "voteOnProject"
  ): TypedContractMethod<
    [projectId: BigNumberish, support: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "wldToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "DonationReceived"
  ): TypedContractEvent<
    DonationReceivedEvent.InputTuple,
    DonationReceivedEvent.OutputTuple,
    DonationReceivedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProjectStatusChanged"
  ): TypedContractEvent<
    ProjectStatusChangedEvent.InputTuple,
    ProjectStatusChangedEvent.OutputTuple,
    ProjectStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalSubmitted"
  ): TypedContractEvent<
    ProposalSubmittedEvent.InputTuple,
    ProposalSubmittedEvent.OutputTuple,
    ProposalSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "DonationReceived(address,uint256,uint256,uint256)": TypedContractEvent<
      DonationReceivedEvent.InputTuple,
      DonationReceivedEvent.OutputTuple,
      DonationReceivedEvent.OutputObject
    >;
    DonationReceived: TypedContractEvent<
      DonationReceivedEvent.InputTuple,
      DonationReceivedEvent.OutputTuple,
      DonationReceivedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProjectStatusChanged(uint256,uint8,uint8)": TypedContractEvent<
      ProjectStatusChangedEvent.InputTuple,
      ProjectStatusChangedEvent.OutputTuple,
      ProjectStatusChangedEvent.OutputObject
    >;
    ProjectStatusChanged: TypedContractEvent<
      ProjectStatusChangedEvent.InputTuple,
      ProjectStatusChangedEvent.OutputTuple,
      ProjectStatusChangedEvent.OutputObject
    >;

    "ProposalSubmitted(uint256,address,string,uint256,uint8)": TypedContractEvent<
      ProposalSubmittedEvent.InputTuple,
      ProposalSubmittedEvent.OutputTuple,
      ProposalSubmittedEvent.OutputObject
    >;
    ProposalSubmitted: TypedContractEvent<
      ProposalSubmittedEvent.InputTuple,
      ProposalSubmittedEvent.OutputTuple,
      ProposalSubmittedEvent.OutputObject
    >;

    "VoteCast(uint256,address,bool,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
