/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { WildlifeDAO__factory } from "./WildlifeDAO__factory";
export { WildlifeDAOToken__factory } from "./WildlifeDAOToken__factory";
